/** Common medicines residents may be prescribed in residential care / recovery programs. */
export const MEDICATION_OPTIONS = [
  { value: '', label: 'Select medicine' },
  { value: 'Paracetamol', label: 'Paracetamol' },
  { value: 'Alaxan', label: 'Alaxan' },
  { value: 'Ibuprofen', label: 'Ibuprofen' },
  { value: 'Mefenamic Acid', label: 'Mefenamic Acid' },
  { value: 'Amoxicillin', label: 'Amoxicillin' },
  { value: 'Azithromycin', label: 'Azithromycin' },
  { value: 'Ciprofloxacin', label: 'Ciprofloxacin' },
  { value: 'Metformin', label: 'Metformin' },
  { value: 'Losartan', label: 'Losartan' },
  { value: 'Amlodipine', label: 'Amlodipine' },
  { value: 'Metoprolol', label: 'Metoprolol' },
  { value: 'Atorvastatin', label: 'Atorvastatin' },
  { value: 'Omeprazole', label: 'Omeprazole' },
  { value: 'Salbutamol', label: 'Salbutamol' },
  { value: 'Cetirizine', label: 'Cetirizine' },
  { value: 'Loratadine', label: 'Loratadine' },
  { value: 'Multivitamins', label: 'Multivitamins' },
  { value: 'Vitamin B Complex', label: 'Vitamin B Complex' },
  { value: 'Folic Acid', label: 'Folic Acid' },
  { value: 'Iron Supplement', label: 'Iron Supplement' },
  { value: 'Calcium Carbonate', label: 'Calcium Carbonate' },
  { value: 'Melatonin', label: 'Melatonin' },
  { value: 'Diazepam', label: 'Diazepam' },
  { value: 'Sertraline', label: 'Sertraline' },
  { value: 'Escitalopram', label: 'Escitalopram' },
  { value: 'Quetiapine', label: 'Quetiapine' },
  { value: 'Risperidone', label: 'Risperidone' },
  { value: 'Haloperidol', label: 'Haloperidol' },
  { value: 'Naltrexone', label: 'Naltrexone' },
  { value: 'Acamprosate', label: 'Acamprosate' },
  { value: 'Disulfiram', label: 'Disulfiram' },
  { value: 'Methadone', label: 'Methadone' },
  { value: 'Buprenorphine', label: 'Buprenorphine' },
  { value: 'Thiamine (Vitamin B1)', label: 'Thiamine (Vitamin B1)' },
  { value: 'Insulin', label: 'Insulin' },
  { value: 'Other', label: 'Other (specify in dosage notes)' },
];
