import { supabase, isSupabaseConfigured } from '@/lib/supabase';

/** Shared admin inbox — auto-generated by DB triggers when a guardian submits a new request. */
export const STAFF_NOTIFICATIONS_CHANGED = 'bh_staff_notifications_changed';

function notifyStaffNotificationsChanged() {
  try {
    window.dispatchEvent(new CustomEvent(STAFF_NOTIFICATIONS_CHANGED));
  } catch {
    /* ignore */
  }
}

/** @returns {Promise<object[]>} */
export async function fetchStaffNotifications({ limit = 30 } = {}) {
  if (!isSupabaseConfigured()) return [];
  const { data, error } = await supabase
    .from('staff_notifications')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(limit);
  if (error) {
    console.warn('[staffNotifications] fetch', error.message);
    return [];
  }
  return data || [];
}

export async function fetchUnreadStaffNotificationCount() {
  if (!isSupabaseConfigured()) return 0;
  const { count, error } = await supabase
    .from('staff_notifications')
    .select('id', { count: 'exact', head: true })
    .is('read_at', null);
  if (error) {
    console.warn('[staffNotifications] unread count', error.message);
    return 0;
  }
  return count || 0;
}

export async function markStaffNotificationRead(id) {
  if (!id || !isSupabaseConfigured()) return;
  await supabase.from('staff_notifications').update({ read_at: new Date().toISOString() }).eq('id', id);
  notifyStaffNotificationsChanged();
}

export async function markAllStaffNotificationsRead() {
  if (!isSupabaseConfigured()) return;
  await supabase.from('staff_notifications').update({ read_at: new Date().toISOString() }).is('read_at', null);
  notifyStaffNotificationsChanged();
}

/** @returns {() => void} unsubscribe */
export function subscribeStaffNotifications(onChange) {
  const handler = () => onChange();
  window.addEventListener(STAFF_NOTIFICATIONS_CHANGED, handler);

  if (!isSupabaseConfigured()) {
    return () => window.removeEventListener(STAFF_NOTIFICATIONS_CHANGED, handler);
  }

  const channel = supabase
    .channel('staff_notifications:admin')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'staff_notifications' }, handler)
    .subscribe();

  return () => {
    window.removeEventListener(STAFF_NOTIFICATIONS_CHANGED, handler);
    supabase.removeChannel(channel);
  };
}

/** Route a related_type to the admin page that handles it.
 *  admission_request goes to the appointment calendar (not the admission list): a new
 *  admission request always carries the guardian's proposed first-meeting date/time, and
 *  that's confirmed/rescheded from the calendar's admission-meeting items, not the list. */
export function staffNotificationTargetPath(relatedType) {
  if (relatedType === 'admission_request') return '/admin-appointments';
  if (relatedType === 'discharge_request') return '/admin-discharge-management';
  if (relatedType === 'visitation_request') return '/admin-appointments';
  return null;
}
